# Generated by Django 4.0.6 on 2023-02-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0005_response_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['-date']},
        ),
    ]
